grommet/grommet-theme-hpe

.circleci/config.yml
package.json
tools/release-stable.js
yarn.lock

Add a script to create a stable branch, so users can point to the master branch of grommet-theme-hpe for preliminary testing of the theme, before the official publishing.

Publish grommet-theme-hpe to a stable branch

---

package.json
webpack.config.babel.js
yarn.lock

Add `grommet-theme-hpe.min.js` as a UMD package, which will allow it to be imported in a wider variety of ways, such as lazily with the grommet-designer.

Added UMD packaging

---

src/js/index.js
yarn.lock

The opacity value for background-contrast dark was too low, so on very dark backgrounds you weren't getting enough contrast to differentiate one element from the next. This slightly increases the opacity to solve this issue while still maintaining the visual effect of `background-contrast` being a "slight contrast" from the background.
This change has been paired with offline discussions with @ericsoderberghp and @L0ZZI

Update background-contrast dark opacity

---

src/js/index.js

This moves any theme updates from the design-system repo as of this week's sprint into the published theme.
The only remaining pieces in the design-system aries.js file are extend functions that utilize normalizeColor function from grommet/utils. @halocline mentioned wanting to think more on if we can implement the extend styling without these functions before thinking about adding grommet as a peer dependency. I have left those aspects of the theme in the design-system theme file for now.

Update from design-system as of 3/12/20

---

src/js/index.js

This PR has resulted from a conversation with @L0ZZI 
The new design shows that the text color on dark mode is #FFFFFF which meets accessibility guidelines better than #EEEEEE.
Simultaneously, we are working on a study for replacing #01A982 as a background color, because even with #FFFFFF text color it is not passing our advanced accessibility requirements, but at least it passes the basic standards and is more complaint than #EEEEEE which fails without question.
See resources:
https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=01A982
vs
https://webaim.org/resources/contrastchecker/?fcolor=EEEEEE&bcolor=01A982

Update text color to meet better the accessibility guidelines

---

src/js/index.js

`global.colors` should be containing only color values or objects with light/dark and color values.

Fixed an issue with global.colors.input

---

src/js/index.js

updated color adds greater contrast and addresses issue #30 and follows color style specified in the Figma color palette
https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-color?node-id=9%3A28

Update background-front dark to 354050

---

src/js/index.js

This updates typography colors and formfield labels/validation to align with the following files:
- [Typography colors](https://www.figma.com/file/oJhw3JqMemtbwWjlLPWW5O/hpe-typography?node-id=0%3A1)
NOTE: I did not update `text` dark to `#DDDDDD` even though the designs call for it because this would cause primary button color (which currently relies on text color) to shift from `#FFFFFF` to `#DDDDDD`. While we could control the label color of primary buttons via the theme, I don't believe we have access to controlling the icon color as well. This should be discussed.
- [FormField](https://www.figma.com/file/E40Oo2MpdRNMyVaJqfJ0Wd/hpe-text-input?node-id=2293%3A2)

Update typography, border colors, and formfield

---

src/js/index.js

Updates formField text to all use color `text` and applies weight `600` to label to create differentiation between label and help text.
Designs call for label with weight `500`, but that doesn't exist in the online font-stack. @gregfuruiye advised using `600` for now.

Update formField styling

---

src/js/index.js

This updates color values/names as well as tab styling (since some is reliant on these values). I am updating everything that has a 1:1 mapping or could easily added but outstanding issues are noted at the bottom of this PR.
The values are coming from here: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=590%3A981

Update colors based on latest swatches

---

src/js/index.js

- Aligned checkbox colors to match designs
- would depend on grommet [change](https://github.com/grommet/grommet/pull/3965) 
https://www.figma.com/file/7Mm1xDBTOtPHqggEVpaD2N/HPE-Checkbox-Component?node-id=1390%3A458
following would be added once grommet is merged in 
```
checkbox: {
box: {
extend: ({ theme }) => `
background-color: ${
theme.global.colors.background[theme.dark ? 'dark' : 'light']
};
border-radius: 4px;
`,
},
}
```

align checkbox theme with designs

---

src/js/index.js

Padding was incorrect for vertical so now should be 6px bottom and top and 12px left and right
color of icon got changed to black for light designs and white for dark so no need to force both to be white

update pad and icon color

---

src/js/index.js

Correcting where Select option pad is placed. Should be `select.options.container.pad`.

fix option vertical pad

---

src/js/index.js

Uses 'text-strong' for Menu icon.
Dependent on this Grommet PR: https://github.com/grommet/grommet/pull/4031

Use text-strong for Menu icon

---

src/js/index.js

since focus is updated with `formfield` I checked behavior and the outline is now on `formfield` and you can still press space bar to uncheck and check checkbox. I just took out border color that `checkbox` came with originally
designs are now having `text-strong` for icon color

update colors take out border focus color

---

src/js/index.js

Apply '#00000080' as the overlay background in both light and dark mode
Design: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=717%3A9

Add overlay background to layer

---

src/js/index.js

Reviewing designs and found the placeholder text should now be using 'text-weak'

Placeholder text to use 'text-weak'

---

src/js/index.js

This will fix the issue with the border color that was found when in focus and error state.
Inserting comment from slack 
> The only things I am seeing are 1) Figma shows formFields having a ‘border-strong’ upon focus, and 2) Figma shows formFields having ‘border-strong’ on error state — currently Designer and Site leave border color as ‘border’ in both of those states.

border for focus and error should be 'border-strong' per designs

---

src/js/index.js

Closes https://github.com/hpe-design/design-system/issues/768
Description:
When `<Select>` was being used without being contained in a `<FormField>` it was receiving extra padding from the `<StyledSelectDropButton>`. Removing the undesired padding.

remove extra padding from select

---

src/js/index.js

Width was set at 100% which was expanding outside the `formfield` parent 
now that width is auto it will not expand past the parent container

add auto for width

---

src/js/index.js

Closes https://github.com/hpe-design/design-system/issues/644
Closes https://github.com/hpe-design/design-system/issues/506
**Summary**
- Serves @L0ZZI's font improvements as MetricHPEXS as opposed to MetricHPE
- Includes upgraded .woff2 format which is supposed to have 30% improvement on compression, with .woff as fallback
- Serving from CloudFront which supports HTTP/2 and is distributed world-wide.
- Includes 'Medium' / 500 weight, which is called for in designs such as [FormField labels](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1)
This is a [preview branch](https://deploy-preview-816--keen-mayer-a86c8b.netlify.app/) pointing to these files.
Would like confirmation that this also solves @L0ZZI's original concern regarding font smoothness.

upgrading font file format, plus serving from CloudFront

---

src/js/index.js

Adds `xsmall` vertical pad to FormField content per designs: https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=78%3A0
Related https://github.com/hpe-design/design-system/issues/818

add vertical pad to formField content

---

src/js/index.js

Closes https://github.com/hpe-design/design-system/issues/843
Closes https://github.com/grommet/grommet-theme-hpe/issues/70
Related to https://github.com/hpe-design/design-system/issues/518
Applies styling to align with [Figma](https://www.figma.com/file/aZyY606ENQedz4FXugdzgS/HPE-Radio-Button-Group-Component?node-id=77%3A323)
Tested on Design System site.
**Screenshots**
**Changes**
- border color
- border width
- check color
- check background color
- checked state border color
- hover state background color applies to entire `<RadioButton>`
- hover state - do not change border color
- narrows gap between check and label

Implement RadioButton theming

---

src/js/index.js

Fixes https://github.com/grommet/grommet-theme-hpe/issues/80
Also need to add `font` and `opacity` to Button documentation and `base.js` on Grommet.

Applying font weight for primary and secondary

---

src/js/index.js
yarn.lock

Closes https://github.com/hpe-design/design-system/issues/985
Removes dependency on extend for RadioButton check background color. Enabled by: https://github.com/grommet/grommet/pull/4266
Testing:
Applied to aries.js theme and Design System site

simplify radiobutton check background

---

src/js/index.js

[Figma designs](https://www.figma.com/file/tMYTr17r6hhGajSlNRiPje/HPE-List-Component?node-id=0%3A1) call for no border between list items by default. This removes the border. Tested locally in design system site.

No border between list items

---

src/js/index.js

Updates `status-critical` to match new colors proposed by Greg. Discussion for this change can be found here: https://github.com/hpe-design/design-system/issues/945
Closes https://github.com/hpe-design/design-system/issues/989

Update status critical color

---

src/js/index.js

This PR adds the color we are using for `formfield` to colors
aries-site
Needed a new color namespace in order to call easily 
https://github.com/hpe-design/design-system/issues/1009

add error validation to color

---

package.json
src/js/index.js
yarn.lock

Update validation-critical placement in file so color names aren't broken up and update yarn.lock to pass CI tests.
Yes.
Just updating placement in file.
Prior merge was failing on build because grommet-icons tarball was out of date.
This would be a breaking change when we merge NEXT into master, it introduces a background color for input field error state. Currently, there is not background color on error in master.
However, this PR does not introduce a new breaking change on the NEXT branch.
If a FormField value does not meet validation requirements, then the FormField will receive a background color of `validation-critical` to indicate that there is an error within that field. The background color is accompanied by error text.

Update validation-critical placement and update yarn.lock

---

src/js/index.js

[Figma](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140)
Updates FormField label and help text margins to complete alignment with Figma - [Issue](https://github.com/hpe-design/design-system/issues/818).
Figma design calls for no spacing between label and help text. Previously, bottom margin was set in the theme at the label, help, error, info levels. This created unwanted spacing when label and help were together. This removes the margin from those elements and transfers the desired vertical margin to the FormFieldContentBox instead.
Yes.
Applied to aries.js on the Design System site. Screenshots below.
This approach was dependent on a change in Grommet FormField to allow for margin to be specified via theme …

update margins based on Slack thread 5-12-2020

---

src/js/index.js

Aligns theme with [Figma Designs]() by removing spacing between radiobutton options when in RadioButtonGroup.
Yes
Applied in aries.js on Design System site. Screenshots below.
This work was enabled by a newly available theme feature. [PR](https://github.com/grommet/grommet/pull/4383)
https://github.com/hpe-design/design-system/issues/897
https://github.com/grommet/grommet/pull/4383
**Before**
**After**
This would be breaking for any projects using RadioButtonGroup. It will remove any gap between radio button options, unless the `<RadioButtonGroup gap="[is specified]" />` is already specified.
Aligns theme with Figma by removing "gap" from between radio button options.

Removes spacing between radiobutton options when in RadioButtonGroup

---

src/js/index.js

Sets `status-error` to undefined since the design-system only uses `status-critical`. The two are very similar, so to avoid improper usage, we are removing `error` from the hpe theme.
Yes.
Tested local on design-system-site
Closes https://github.com/hpe-design/design-system/issues/980
Breaking change.
Any usage of `status-error` should be changed to `status-critical`.

Remove status-error since we use status-critical

---

.github/PULL_REQUEST_TEMPLATE.md
src/js/index.js

This PR adds margin for top and bottom of drop 
yes
design system to match figma files
https://github.com/hpe-design/design-system/issues/657
issue #657 on design system
This should be added that previously there was no margin between `textinput` and `drop` and now it is 6px

add margin to drop

---

src/js/index.js
yarn.lock

- Corrects `status-critical` colors (previously transposed)
- Updates `status-warning` to match Figma
- Updates `status-warning` to match Figma
[Figma](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=590%3A1055)
NEXT
Compared values in theme to Figma.
https://github.com/hpe-design/design-system/issues/1059
Updates to colors which were already breaking.

Update status colors to figma

---

src/js/index.js

Updates rangeinput to use new grommet functionality of `track.upper.color` and `track.lower.color` to style rangeInput track.
When cross checking with designs, designs show RangeInput inside of a FormField, but these theme styles apply purely to the rangeInput: https://www.figma.com/file/BqCjvjc0rECQ4Ln2QhyjNi/HPE-Range-Input-Component?node-id=1%3A50
Yes.
Tested local in design system site. See screenshots below.
This is a breaking change.
- **Track color**: 
- upper: `border` (previously black)
- lower: `green` (previously black)
- **Thumb:**
- background color: `background
- border: 1px solid `border`
- elevation: small

Update rangeInput to match site

---

README.md

npm fails to install from a branch.  Use yarn instead.
See issues #78 and #99.
Update README to use yarn when installing from a branch.
Yes.
Markup preview.
No.
See issues #78 and #99.
N/A.
Yes.
Updated README.md.

README: yarn required for branches

---

src/js/index.js

Select, when not inside a FormField, didn't have any disabled styling. While we may want to expand the theming capabilities for this in grommet, for now we are just applying this via theme extend. When Select is disabled, it toggles opacity to 0.3 (matching grommet default for disabled) and keeps cursor as the default as opposed to pointer.
Yes.
Test local in design system site.
Closes https://github.com/grommet/grommet-theme-hpe/issues/96
Compatible.

Fix Select disabled styling

---

package.json
yarn.lock

Moved grommet-icons from dependency to peer-dependency
The thought behind this PR is that the theme will run on top of grommet core, which will determine the grommet-icons version. Hence, the theme will only build the icons package on dev mode and will rely on the user to resolve the actual icons version package as a peer dependency.

Moved grommet-icons from dependency to peer-dependency

---

src/js/index.js
yarn.lock

Transfers the Card theming that was living locally in the design system site over to the theme. This makes the default padding and other values align with what is shown in designs. However, users would still have the ability to override these via props if needed in certain use cases.
For those that are not applying any padding on their Cards, this would introduce padding. However, if they have already supplied their own custom padding then this wouldn't affect.

Add card to grommet theme hpe

---

src/js/index.js

[Design](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=0%3A1)
On hover and active, Tab label should still be `text-strong`, right now it was `text`. Aligning with designs.
Tested locally on design-system site. 
Before:
After:
Updates the active/hover colors
When active or hovered over, a Tab label will now have color of `text-strong` as opposed to `text`.

Update tab label color for various states to match design

---

src/js/index.js

Utilizes `radioButton.container.extend` for proper theming.
Yes.
Test in design-system site.
Grommet was applying `radioButton.extend` to two DOM elements but is not creating a separate theme object for `radioButton.container.extend`
https://github.com/grommet/grommet/pull/4361
Breaking change.
Already documented in [theme migration guide.](https://github.com/grommet/grommet-theme-hpe/wiki/Migration-guide-to-the-design-system-theme#radiobutton). However, this functionality is dependent on the merge of https://github.com/grommet/grommet/pull/4361 in grommet core.

Use radioButton.container

---

package.json
yarn.lock

Update peer dependency to grommet v2.15.2, to include the fix for `radioButton.extend`.
Related to #120 
#120 
Grommet elaborates on this change on its release notes. https://github.com/grommet/grommet/releases/tag/v2.15.2
https://github.com/grommet/grommet/releases/tag/v2.15.2

Updated peer dependency of grommet and dependencies

---

src/js/index.js

Updates label color of buttons to use `text-strong` to align with Figma designs.
[Designs](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1)
Tested locally in design system.
Updates were made the Figma file that were not reflected in grommet-theme-hpe.
Button uses `text-strong` as opposed to `text` for label color.

Update button label to use text-strong

---

src/js/index.js

The HPE design-system is providing three options for text colors: `text`, `text-weak`, `text-xweak`.
Though, HPE users still see the `text-xweak` option from the base theme. This PR is restricting the use of this base theme color.
This PR results from a question we've received from GLC:
> I noticed that there is a text-xweak defined in the base grommet theme, but not in the hpe theme - and it is darker than the new text-weak is. Should the hpe theme also be specifying text-xweak so that it is relatively weaker than text-weak?
Might be an issue for HPE users that have used `text-xweak`, the value will be turned to 'undefined'.
Restricting the usage of `text-xweak` as this color isn't supported by the HPE design-system.

Restraining the use of text-xweak

---

.babelrc
package.json
yarn.lock

- Add React as peerDependency to support JSX in theme
- modifies babel configs to support build with JSX
This work will allow `index.js` to specify icon values requiring JSX in the theme and enable progress on issues such as:
- https://github.com/grommet/grommet-theme-hpe/issues/126
- https://github.com/grommet/grommet/issues/4465
- Built grommet-theme-hpe using `yarn build`
- Used the compiled `/dist` as `node_modules/grommet-theme-hpe` and verified desired icons appeared.
Assuming `/grommet-theme-hpe` and `/aries` are siblings in the same directory, from `aries-site` directory:
```
rm -r ../node_modules/grommet-theme-hpe && cd ../../grommet-theme-hpe && yarn build && cd ../aries/aries-site && cp -r ../../grommet-theme-hpe/dist ../node_modules/grommet-theme-hpe && yarn start
```
- …

Add React as peerDependency to support JSX in theme

---

.eslintrc
src/js/index.js

- Adding radioButton check icon per designs
- turned off eslint rule for no jsx in .js files
- closes https://github.com/grommet/grommet/issues/4465
- Closes https://github.com/grommet/hpe-design-system/issues/851 which calls for a larger check/circle in selected radio buttons.
- Closes https://github.com/grommet/grommet/issues/4465 which asked for ability to specify the check size in the theme. Instead, was asked to try to use the `radioButton.icons.circle` property in the theme which had previously been [undocumented](https://github.com/grommet/grommet/pull/4581).
Design System site.
Above.
https://github.com/grommet/hpe-design-system/issues/851
https://github.com/grommet/grommet/issues/4465
Backwards compatible, but should be mentioned in the style changes portion of the [migration …

Adding radioButton check icon per designs

---

src/js/index.js

Adds `CircleAlert` icon to FormField error to align with [Figma Designs](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1).
Already implemented locally in DS site.
Closes https://github.com/grommet/grommet-theme-hpe/issues/126
Backwards compatible, but will introduce a new icon next to the text that wasn't there previously. Have added to theme migration guide that this is a style change: https://github.com/grommet/grommet-theme-hpe/wiki/Migration-guide-to-the-design-system-theme#formfield

Add icon to formfield error

---

src/js/index.js

Inputs call for an icon of color `text-strong` by default. This sets that value in the theme so users don't need to set it on each implementation.
Design example can be seen on DateInput: https://www.figma.com/file/Mf9if6zyGETTWW5b9PsYNQ/HPE-Date-Input-Component?node-id=0%3A1
Test locally in design system site.
New visual, but not breaking.
By default, icons used in inputs now use `text-strong` instead of `text`.

Set default input icon color

---

src/js/index.js

`status-disabled` is not being used anywhere in the theme except its definition and it is not being used in any of the design system designs. in cases of disabled, either `text-weak` or `border-weak` is used. This adds a comment that marks this as deprecated and provides guidance on which color should we used instead.
Closes https://github.com/grommet/hpe-design-system/issues/1103
`status-disabled` should not be used. Instead, use `text-weak`.

Mark status-disabled as deprecated

---

src/js/index.js

Adjust input weight to match designs. Input value calls for 500 and placeholder calls for 400. The `global.input.extend` is currently only present on grommet stable (not a released version), so we won't see these changes in effect until the next grommet release.
Tested locally on DS site.
Closes https://github.com/grommet/hpe-design-system/issues/1005
New visual look but not a breaking change.
Input value uses weight of 500 (medium) and placeholder uses weight of 400 (normal).

Update placeholder weight and input value weight

---

src/js/index.js

Marks `disabled-text` as deprecated and instructs users to use `text-weak` instead. Updates value of `disabled-text` to `text-weak` just to be consistent. Updates 2 instances of disabled border to use `border-weak` instead of `text-weak` just for semantic alignment.
Tested locally in DS site.
Closes https://github.com/grommet/hpe-design-system/issues/1102
`disabled-text` is deprecated. Use `text-weak` instead.

Mark disabled-text as deprecated

---

src/js/index.js

CheckBoxGroup and RadioButtonGroup call for `xsmall` space on top and bottom, but individual checkbox should fully fill the formfield. This adjust the styling to the margin comes from the `RadioButtonGroup` and `CheckBoxGroup` themselves as opposed to the FormField.
Two additional clean-ups:
1. checkbox border was being `unset` which did't allow the border color to be applied properly. this has been removed.
2. radiobutton and checkbox call for labels to be weight of 500. this PR applies that.
Tested locally in aries-site.
Checkbox on hover was not filling the formfield fully, this did not align with designs.
Closes https://github.com/grommet/hpe-design-system/issues/1246
This is backwards compatible. There will be a visual change where now individual checkbox hover background will fill …

Adjust grouped input theming

---

src/js/index.js

Modifies FormField margins to align with Figma by adjusting where margins are applied.
[Figma](https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=54%3A14) calls for 12px of spacing between form fields. However, this spacing was too large in certain circumstances (18px instead of the desired 12px).
The old way:
- formField label, help, error, info had zero margin
- `formField.content.margin.vertical` = 6px
- `formField.margin.bottom` = 12px
This resulted in scenarios where if there were no error message, the spacing between that FormField and the following would have 18px of spacing in between (6px from `formField.content.margin.bottom` + 12px from `formField.margin.bottom`)
The new way:
- `formField.label.margin.top` = 6px
- `formField.error.margin.bottom` = 6px …

Modify FormField margins to align with Figma

---

src/js/index.js

Applies DataTable and Table styling.
Closes: https://github.com/grommet/grommet-theme-hpe/issues/143
This styling has been live on the Design System site for several weeks. Vicky and I did a side-by-side review confirming the styling alignment. No changes were made. We did identify a couple of areas which she wanted to explore more, but those were not theme related.
Production [Design System site](https://design-system.hpe.design/components/table) is best place to visually review.
https://github.com/grommet/hpe-design-system/issues/1219
Backwards compatible. Introduces new styling which had not yet been released.
Implemented theming for tables.

Incorporate datatable styling

---

src/js/index.js

Sets Layer default elevation to large to match designs. Dependent on functionality currently only provided in grommet stable.
Tested locally in design system site.
Closes #149 
Backwards compatible, but introduces new default elevation to align with Figma.
Layer applies elevation "large" by default.

Set default layer elevation to large

---

src/js/index.js

Updates heading to use `text-strong` instead of `text`.
Tested locally in design system site first. See snapshots below.
A design decision was made to use `text-strong` for headings by default.
Closes #152 
Pulled these as some examples, for all snapshot tests, see: https://eyes.applitools.com/app/test-results/00000251790534341231?accountId=diU-zN8vi0mdpzHhZndu1A~~&display=details&top=00000251790534341231%2830%29
Before:
After:
New visual style.
Heading uses `text-strong` by default.

Use text-strong for headings

---

src/js/index.js

Align Card default elevation to Figma with value of `medium`. Align elevation values to Figma. The HEX value for elevation.light.medium and elevation.light.dark had been reversed.
Card: https://www.figma.com/file/je5AYzMavRt1cG7rmw8j1W/HPE-Card-Component?node-id=1%3A2
Colors: https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/HPE-Color-Styles?node-id=0%3A1
Tested locally in design system site.
Closes https://github.com/grommet/hpe-design-system/issues/1376
New default elevation value, but aligns theme to Figma.
Card uses elevation `medium` by default.

Set default card elevation to medium and fix elevation hex value

---

src/js/index.js

Apply border radius `small` to Layer and use `intelligentRounding` so that if the edge of a Layer is touching the edge of a screen (such as full Layer), there will not be rounding. Dependent on functionality that is currently only on grommet stable.
Tested local in site first.
Closes https://github.com/grommet/hpe-design-system/issues/1341
Aligns with Figma.
Layer border-radius updated to have value of `12px`.

Apply border radius to layer to match Figma

---

.circleci/config.yml
package.json
src/js/index.js

We had previously created release-github-pages to respond to NEXT branch, but that functionality was lost once we merged NEXT into master. This aims to publish the updated theme to github pages for use with grommet designer anytime there are changes.

Add back in gh pages release

---

src/js/index.js

Updates tab styling for active state and increases horizontal padding to create better affinity between tab icon + label.
Tested locally in aries-site.
Closes #146 
Closes https://github.com/grommet/hpe-design-system/issues/1363
Closes https://github.com/grommet/hpe-design-system/issues/1385
Introduces new tab styling.
Active tabs have a "medium" width border of border-strong and increased horizontal padding from "small" to "medium".

Update tab styling for active state and padding

---

src/js/index.js

Display an * next to required formfield labels. Once this merges, we will need to remove custom label components in the design system site that had been providing the *
Tested local in design-system site.
Design decision backed by this best practice: https://www.nngroup.com/articles/required-fields/
Introduces new visual change.
Added asterisk * next to required FormField labels.

Display * next to label of required FormField

---

src/js/index.js

Removes the padding overrides in the button 'kind'-specific parts of the
theme and allows the button 'size' part of the theme to specify them.
Grommet v2.16.3 correctly adjusts the padding to account for any borders
added by the 'kind' styles, avoiding the need to have kind-specific padding.
Tested in grommet with this theme.
Fixes #139
Before theme fixes:
After theme fixes:
Can mention that button sizes now work correctly with this theme

Removed the button kind paddings as part of fix for button sizing #139

---

src/js/index.js

Button size medium should have horizontal pad `12px` and vertical pad `6px`. When we removed the kind specific padding, we lost this styling.
Total height of default button should be 36px. https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1
Test local in DS site.
Currently (Default/Medium button have improper dimensions):
With correction (Default/medium correct dimension of 36px tall):

Update button medium pad

---

src/js/index.js

Add the tooltip theme to match the designs.
Currently, the designs call for  `medium` elevation. However, it does not look correct with the medium so  I replaced it with small and will follow up on an issue. 
With medium, the bottom shadow is very harsh.

add tooltip

---

src/js/index.js

Aligns Menu drop with [Figma](https://www.figma.com/file/DyFWlzLBUtK5KH5jJhwoCB/HPE-Menu-Component?node-id=0%3A1) where drop should be aligned `{ top: 'bottom', left: 'left' }`
Tested local in design system site
Closes https://github.com/grommet/hpe-design-system/issues/1416
New drop alignment.
Aligned Menu's Drop alignment with Figma. Drop appears below the control button.

Set default menu drop alignment

---

package.json
yarn.lock

This PR updates react version
I tested this with `npm link` and then the dist folder was copied into a create react app that I had running locally. I ran `npm install` and got no error.
We can always merge this to another branch besides master to be able to fully test the `npm install grommet-theme-hpe` since I  could only run `npm install` after the dist folder was pasted into my node_modules.
Starting from npm 7, peerDependencies are automatically installed together with normal dependencies. When npm finds a version mismatch, a problem arises because it will abort the installation. grommet-theme-hpe has react dependency of react: 16.13.1. However, if someone is using React 17 or above, a mismatch will be detected and the installation will be aborted.
Recommended solution is to change …

update react version

---

src/js/index.js

use new intelligent margin from grommet
Adds `intelligent margin` to theme both `search` and `tooltip` are `xsmall` margin and now with the new `intelligent margin` the side in which the margin is placed is accurate.
design system local theme
```
global: {
drop: {
margin: 'xsmall',
intelligentMargin: true,
background: 'background-front',
border: {
radius: '4px',
},
extend: () => {},
},
},
```
https://github.com/grommet/hpe-design-system/issues/1449

clean up drop margin

---

src/js/index.js

Closes https://github.com/grommet/grommet-theme-hpe/issues/184
Local project implementation with the Global header service.
https://github.com/grommet/grommet-theme-hpe/issues/184
https://github.com/grommet/grommet-theme-hpe/issues/184
bc

Adjust Layer z-index to sit atop HPE global header

---

src/js/index.js

Closes https://github.com/grommet/grommet-theme-hpe/issues/187
Tested locally with `<Select />` within a `<Layer />`. However, I think we should do more exhaustive testing to check for edge cases and different combinations of components presented in a Layer.
I could use help brainstorming any other potential areas which might have unintended side effects do to the increased zIndex.
Since we are trying to release the theme, we may want to revert https://github.com/grommet/grommet-theme-hpe/pull/185, then use this implementation in another project to test on the side over an extended period of time.
Originally trying to solve for the HPE Global Header Service which has a `z-index` of 101 and prevents Layer from filling window properly.
https://github.com/grommet/grommet-theme-hpe/issues/184 …

Align Drop and Layer zIndex

---

src/js/index.js

Adds FileInput styling per Figma Designs https://www.figma.com/file/8HwAiiSDloOTjUxqvCTypq/HPE-FileInput-Component?node-id=218%3A45549
Tested in DS site.
(mouse was hovering over "Select File" button)
Added FileInput styling.

Add FileInput styling

---

src/js/index.js

This adds a button kind `toolbar` for the button kind featured below. Currently, this kind of button is always used in a toolbar context where it is inline with inputs such as a Search and the desire is that it has equal prominence as its peers.
Test in DS site.
Closes https://github.com/grommet/hpe-design-system/issues/1118
Added `toolbar` button kind.

Add toolbar button kind

---

src/js/index.js

Need to set hover color to undefined to ensure color stays as text-strong on hover. Mirroring what is done on default button.
Tested locally in DS site.
no.

Keep text-strong color on hover

---

src/js/index.js

We can use `radioButton.hover.background.color` to apply the hover background as opposed to extend. This will allow us to leverage radioButton keyboard enhancements.
DS site local, tabbed to FormField then used arrow keys to navigate:
Focus/keyboard indication was not showing up on radiobuttongroup correctly.
No visual change from styling, just used new theme object.

Leverage new RadioButton theming

---

src/js/index.js

Now that we have [enhanced Grommet](https://github.com/grommet/grommet/pull/5288) to better handle focus behavior of checkboxes, we can remove this from the extend. Previously, we had been removing the border since most CheckBoxes are displayed within FormFields, but this was causing accessibility issues in cases where CheckBox is outside of FormField. We no longer have this conflict.
Tested in DS site. Checkbox outside of FormField receives focus on check. Checkbox inside formfield receives hover treatment.
Fixed CheckBox focus behavior to have focus outline when outside FormField.

Update CheckBox theming from latest grommet enhancements

---

src/js/index.js

Figma calls for color of `border` for Accordion. Updating to match.
In DS site.
Aligning to Figma.
Fixed Accordion border color to align with Figma.

Update accordion border color to match Figma

---

src/js/index.js

Figma calls for `FormNext` and `FormPrevious` in Calendar on all viewport sizes. Updating to match.
Local in DS site.
Related to https://github.com/grommet/hpe-design-system/issues/1676
New icons, but just smaller.
Fixed Calendar icons to use FormNext and FormPrevious to match Figma.

Update Calendar Icons

---

src/js/index.js

This PR adds a background that has a opacity for `datatable` for just FireFox browser
Browser
We were using  `backdrop-filter: blur(8px)` however FireFox does not support `backdrop-filter:`
so as an alternative I thought adding a background will at least make the `datatable` more readable 
closes issue #200 
Currently looks like this below: 
With the background:
Does not have that nice effect as chrome but at least now its much easier to read:
In Chrome:
sure

add alternative background for Firefox 

---

src/js/index.js

This PR changes the padding for the `input` this takes into account the border for the inputs. The size of the `textinput` without being wrapped in a `formfield` is `38px` with wrapping it in a `formfield` then it uses the `textinput` plain so without the border and is then the correct size.
in the design system site
Below is a picture of the sizes for `button` the padding is off by one to account for the border. I believe we need to do the same for the `inputs` as well. Since `Select` and  `Menu` are made from `button` their sizes are correct. 
With this change to the padding you can see that they both will match up correctly. 
Closes https://github.com/grommet/hpe-design-system/issues/1778

change the padding to take into account the border

---

src/js/index.js

Leverages Grommet's more recent intelligent background for datatable pinned cells. Thus we can remove the "background-front" declaration and let the datatable be smart about what background it's on.
Updating the opacity from 'strong' to 0.95 so it works for all browsers (Firefox included). This does make the blur slightly less apparent in Chrome but I think the difference is minimal and creates a more readable table.
Tested locally in DS Site.
Closes #206 
Note: these are static images, the blur is more visible when user is actually scrolling.
Makes the opacity on the pinned cells from 0.8 --> 0.95 but fixes incorrect color treatment/makes behavior more consistent from firefox to chrome and other browsers.
- Fixed pinned DataTable background color

Update pinned DataTable background

---

src/js/index.js

This PR  aligns RangeInput with the [Figma file](https://www.figma.com/file/BqCjvjc0rECQ4Ln2QhyjNi/HPE-Range-Input-Component?node-id=0%3A1)
aries-site
RangeInput was the color of `background` before with a `border` on hover which was hard to see so the designs were changed to align more with grommet.
closes #1892
in design system
yes

align theme with figma file for rangeinput

---

src/js/themes/hpe.js

Adds hover styling for Card to theme where if Card has a singular onClick, it will have an elevation change to large on hover.
Tested locally in DS site:
https://user-images.githubusercontent.com/12522275/140003506-a89e6e63-e572-4780-8f0f-371f9756fa8e.mov
Related to https://github.com/grommet/hpe-design-system/issues/1902
New hover treatment to align with Figma.
Added Card hover elevation treatment for Cards with `onClick`.

Add Card hover elevation treatment to theme

---

src/js/themes/hpe.js

This PR aligns label for `checkbox` so when there is multi-lines it is aligned start
tested with aries.theme in design-system
currently we have:
what we want:
closes https://github.com/grommet/hpe-design-system/issues/2000
look above
no
yes

align label to be start

---

src/js/themes/hpe.js

this PR adds new hover behavior for `button`
closes https://github.com/grommet/hpe-design-system/issues/2122
yes

add hover for primary button

---

src/js/themes/hpe.js

This PR changes the gap between the icon and label to be `xsmall`
design system testing
per [Figma](https://www.figma.com/file/Oi5UEEQ33VCAyOKQcZ8Nr8/HPE-Button-Component?node-id=0%3A1) the `gap` should be `xsmall`

align button gap with figma to be xsmall

---

src/js/themes/colors.js
src/js/themes/hpe.js

This PR goes through and changes the current values we have for `text-weak` to `text-xweak`
tested this in the design system 
anything that was `text-weak` should be `text-xweak`
closes https://github.com/grommet/hpe-design-system/issues/2312

change the places we have text-weak to text-xweak

---

src/js/themes/hpe.js

This PR changes the `text` in the select options to have a weight of 500
site
match what is on figma 
closes https://github.com/grommet/hpe-design-system/issues/1242

Change Select options font weight

---

src/js/themes/hpe.js

Added the correct min page width to the theme. The grommet base theme uses t-shirt sizing for the min width but the hpe theme uses 336px for its min width.
Note: once the hpe theme has xsmall and xlarge breakpoints the page theme will need to be updated to include these.
Theme was tested in https://github.com/grommet/hpe-design-system/pull/2439 and https://github.com/grommet/hpe-design-system/pull/2433
https://github.com/grommet/hpe-design-system/issues/2426
backwards compatible (page hasn't been released on grommet yet)

Added correct page width for hpe to the theme

---

src/js/themes/hpe.js

fix color for Toast notifications 
design system site
brought up in slack
change backward
what it was before

add background for toast

---

package.json
yarn.lock

Upgrade to use react v18.0.0
https://github.com/grommet/hpe-design-system/issues/2538
backwards compatible
Added support for React 18

Upgrade to React 18

---

src/js/themes/hpe.js

Adds theming for Page Header elements
Implemented on DS site PR: https://github.com/grommet/hpe-design-system/pull/2574
Related to [#2562](https://github.com/grommet/hpe-design-system/issues/2562)
Related to [#2603](https://github.com/grommet/hpe-design-system/issues/2603)
Added NEW PageHeader styling.

Add page header theming

---

src/js/themes/hpe.js

adds `column` to be the default for direction with Toast notification
tested with grommet storybook
Talked with @kenny and even though Title is optional for a toast notification if provided it should be above the message not inline 
closes https://github.com/grommet/grommet/issues/6209

add direction for toast message

---

src/js/themes/hpe.js

A first cut changes to the theme to add a CTA kind for Button and round the buttons.
- Removes the HPE specific Button border radius settings and lets the base rounded buttons be the style.
- Adds  a `cta` kind for the Call To Action button style with the brand coloring and a hover style similar to the primary button. Note that primary buttons and secondary button borders are a brighter green than the brand color.
What this doesn't address:
- Embedding the HPE element icon within the styling
- Some form of animation of the element on hover
https://github.com/grommet/hpe-design-system/issues/2779
https://github.com/grommet/hpe-design-system/issues/2774
Not really a breaking change but it is a significant visual difference to existing buttons including drops' hovers and such.

First cut at Button changes for the HPE Brand refresh

---

src/js/themes/hpe.js

- cta --> 'cta-primary'
- adds 'cta-alternate'
- adjusts icon vertical align from 'middle' to 'text-bottom', decrease icon height, to ensure that icon+label are aligned but button doesn't exceed 36px
- adds back size definitions which were needed to ensure button is properly sized
local in DS site, see screenshots
Closes https://github.com/grommet/hpe-design-system/issues/2774

Update cta to add alternate flavor

---

src/js/themes/colors.js
src/js/themes/hpe.js

Adds HPE element to cta-primary and cta-alternate buttons. Leverages new grommet capabilities re: kind-specific padding to adjust padding for the CTA buttons at various sizes.
Updates secondary and primary buttons to use `brand` green.
Updates label font size/line height of buttons to align with brand.
Local in aries site -- see screenshots below.
Closes #271 
medium, 36px
large, 42px
xlarge, 48px

Add HPE icon to CTA buttons and update kind-specific padding

---

src/js/themes/hpe.js

updates active state in Tab 
Based on user research we have decided to modify the active state tab to increase user recognition time.
DS site
Based on user research we have decided to modify the active state tab to increase user recognition time. The new active state can be found here: https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=4317%3A40074
The `6px` is not a t-shirt size for border however we go from 4px to 12px so not sure where we can meet in the middle
closes https://github.com/grommet/grommet/issues/6292
it would change the active look
release notes

update tab active state

---

src/js/themes/hpe.js

This PR uses the `checkBox.pad` to set values instead of the `extend`
design system site
```
checkBox: {
pad: {
vertical: 'xsmall',
horizontal: 'small',
}
extend: ({ disabled, theme }) => `
${
!disabled &&
`:hover {
background-color: ${
theme.global.colors['background-contrast'][
theme.dark ? 'dark' : 'light'
]
};
}`
}
font-weight: 500;
width: auto;
};
`,
},
```
paste into aries theme to test 
users will need to use `pad` prop to overrid the theme Padding
closes https://github.com/grommet/hpe-design-system/issues/2810
pad fixed for checkbox outside formfield

update checkBox.pad to use values from extend

---

src/js/themes/hpe.js

- Apply `6px` rounding to buttons medium & small, controls (text input, date input etc.)
- Apply `8px` rounding to large button (0.5 * horizontal padding)
- Apply `10px` rounding to xlarge button (0.5 * horizontal padding)
- Apply `6px` rounding to FormField
- Apply `4px` rounding the CheckBox
- Adjust hover treatment on primary button to align with "darkened" treatment on CTA-primary
DS site
Confirming Select option buttons render full-bleed:

Apply adjusted rounding to controls

---

src/js/themes/hpe.js

For primary buttons, the label color is set to "white" so that it is consistent on the brand green regardless of theme mode. However, for primary + color buttons, we want the label color to respect the theme mode and use the appropriate mode of  `text-strong`.
Locally in Design System site (see screenshots below)

Account for color on primary button

---

src/js/themes/hpe.js

This PR adds new hover treatment for `checkbox`
ariess-site
**Not in form field**
- No padding
- Hover treatment border goes from default —> border-strong
**In FormField**
- Padding
- Hover treatment: background-contrast
- Hover treatment border goes from default —> border-strong
**In DataTable**
- Padding
- Hover treatment: background-contrast
- Hover treatment border goes from default —> border-strong
closes https://github.com/grommet/hpe-design-system/issues/2862
https://user-images.githubusercontent.com/12522275/194620800-21bb5879-a939-487f-a833-d7ab920bc354.mov

add new hover treatment

---

src/js/themes/hpe.js

Updates FileInput message (placeholder text) to use `placeholder` to stay in sync with other input placeholder colors.
Closes https://github.com/grommet/grommet-theme-hpe/issues/284

Update FileInput message to use placeholder

---

src/js/themes/hpe.js

Updating grouped menu theming to remove pad around separator and to change separator color to `border`.
Tested locally in DS site.
Closes https://github.com/grommet/hpe-design-system/issues/2964
Updated grouped Menu styling to remove padding around separator.

Update grouped menu theming

---

src/js/themes/hpe.js

This PR changes `large` to be 96px for Avatar size 
aries site
designs call for 96px for large 
changes can also be seen here below in the deploy 
https://deploy-preview-2982--keen-mayer-a86c8b.netlify.app/components/avatar

large size for avatar

---

src/js/themes/hpe.js

Apparently the typography direction is recommending two font scales:
- One for web (larger)
- One for product (smaller)
This PR to merge into NEXT is adjusting Heading sizes to fit the [product scale](https://www.figma.com/file/DzR2LCNtbuZvomp1DOOGMR/HPE-GreenLake-Brand-Refresh?node-id=616%3A31632&t=Q1h8JGskLnTRtzoc-4).
Leaving the "web scale values" commented out so that we can reapply them easily.
In the longer term, if we are going to be supporting multiple scales, we might want to consider a new theme repo for `grommet-theme-hpe-web` or something along those lines. This could be a `const hpeWeb = deepFreeze({ // font size overrides }, hpe);`

Product typography

---

src/js/themes/hpe.js

adds color or thumbRating and starRating then fix the spacing between label 
aries site
match figma
Closes https://github.com/grommet/grommet-theme-hpe/issues/299
https://deploy-preview-3076--keen-mayer-a86c8b.netlify.app/templates/user-feedback-collection
yes

add theme changes for survey starrating thumbrating

---

src/js/themes/hpe.js

Based on outcomes of https://github.com/grommet/hpe-design-system/issues/2990, reverting the theme to point to brand central font version. The URLs were provided by Artur's team. I had to explicitly define regular as font-weight 400 otherwise it wasn't applying it.
Tested locally in the site on Mac Chrome, Windows Edge:
Mac Chrome:
New font, Windows Edge (notice how the "i" is differentiable from "l", j has a visibly separate dot)
Closes https://github.com/grommet/hpe-design-system/issues/2990

Use Brand Central font versions

---

src/js/themes/hpe.js

Adds `iconOnly` padding for button (values may need to be refined in relation to Chris's explorations on icon sizing, but setting this for now to replace what we currently have in extend).
Also, removed unnecessary overrides for cta-primary/alternate that were lingering from a previous merge.
Adds `backdropFilter` to Layer overlay and removes extend.
NOTE: Toolbar icon only button padding changes with this, but in discussion with Eric we felt like this change was reasonable and in the spirit of the new direction. Feedback welcome.

Apply iconOnly and layer backdropFilter enhancements

---

src/js/themes/hpe.js

To align with other styling like NameValueList / Header cells in DataTable, adjust notification title to use weight `500` and color `text-strong` as opposed to bold.

Update notification title styling

---

package.json
tools/release-gh-pages.js
tools/release-next-stable.js
tools/release-stable.js
yarn.lock

To align with grommet, leave `del` at v6.1.1. This PR also fixes the simple-git syntax. Removing `silent(false)` from git because it is deprecated after v2.7.0 of simple-git.
I tried this locally by commenting out the check for CI environment and the release-gh-pages script passed (I did not include the commit/push lines, so nothing should show up in CI environment yet).

Downgrade del, resolve simpleGit syntax

---

.circleci/config.yml
README.md
package.json
tools/release-audit-stable.js

Closes https://github.com/grommet/hpe-design-system/issues/3155 by adding `release-audit-stable` ci/cd step for CircleCI to run against the AUDIT branch.
Intended to aid conducting brand and design system audits.
https://github.com/grommet/hpe-design-system/issues/3155

Add release-audit-stable ci-cd step

---

src/js/themes/colors.js
src/js/themes/hpe.js

This PR:
- Adjusts icon sizing to align with font-size as opposed to line-height at each size
- Restores Button extend for label size to 19px to meet AA contrast requirement
- Removes border from toolbar buttons, but leaves 6px rounding to have parody with inputs they are presented alongside
- Adjusts checkbox, radiobutton, and select "selected" state to use brand green. To meet color contrast for Select selected option, increases font-weight on selected item to 700 (aligns with Button).
- Tab styling based on [conclusions in this file](https://www.figma.com/file/KYjfAybRakWLOe2GLAHDHV/Tabs-variations?node-id=0%3A1&t=uMKWBZm1a62HvxIs-0).
Related to #308

Add theme adjustments to align with latest discussions

---

src/js/themes/audit.js
src/js/themes/hpeMark.js
src/js/utils/deepMerge.js
src/js/utils/index.js

Creates an audit theme for use when conducting brand audits. Callers will reference the AUDIT-stable branch from their `package.json` and then apply the audit test by using the `audit` theme.
```
import { audit } from 'grommet-theme-hpe';
...
<Grommet theme={audit} ... />
```
https://github.com/grommet/hpe-design-system/issues/3154

initial audit theme and rules

---

src/js/themes/hpe.js

Fixes an issue where icons in notifications are not vertically centered.
Before:
After:
Tested by adjusting the theme in grommet's Notification/Status story
https://github.com/grommet/grommet-theme-hpe/issues/319
backwards compatible

Remove extra padding from notification icon container

---

src/js/themes/hpe.js

Fixes an issue where SelectMultiple `showSelectedInline` checkmark icons were not centered on small screens.
Before:
After:
Tested by adjusting the theme in the grommet SelectMultiple/ShowSelectedInline story
https://github.com/grommet/grommet-theme-hpe/issues/319
Backwards compatible

Adjust select icon margin

---

src/js/themes/hpe.js

There is an extra 3px top margin on the close button for tags. This PR removes the extra margin.
https://github.com/grommet/grommet-theme-hpe/issues/319
Backwards compatible

Remove extra margin from tag remove button

---

src/js/themes/hpe.js

Instead of defining on each kind, set default button radius to 2em. This allows us to leave `default` button radius as `undefined` so the badge aligns to the label/icon instead.

Set default radius to 2em

---

src/js/themes/colors.js
src/js/themes/hpe.js

This PR reverts changes to the modal layer overlay.

Revert layer overlay changes

---

src/js/themes/hpe.js

Corrects location of `color` property for `pagination.button.active`

Pagination button active font color

---

src/js/themes/hpe.js

Updates the DataTable contract/expand icons for `groupBy` to use Down/Up instead of form icons. Height "medium" ensures the icon is vertically-aligned with the other content in the row.

Update DataTable contract/expand icons

---

src/js/themes/hpe.js

Adjusts small icon-only padding to `10px` to ensure `36px` dimensions. Reverts changes to icon format from #342 which was causing error/not rendering icon.

Fix small icon-only padding and icon rendering

---

src/js/themes/hpe.js

Updates DataTable header units to use "text-weak" to meet accessibility contrast requirements.
Local in DS site.
Closes #326 
Updated DataTable units color to meet color contrast requirements.

Update DataTable units to use text-weak

---

src/js/themes/hpe.js

When upgrading to 5.0.1, GLCP reported an error in their Jest test suite: `undefined:1:1232: property missing ':'` related to a checkbox test.
https://github.com/styled-components/jest-styled-components/issues/97#issuecomment-364169127 pointed to https://styled-components.com/docs/api#css as the solution.
Most discussion points to the styles being rendered correctly in browsers, but throwing errors in certain Jest environments.
Built project locally and consumed in GLCP/frontend/ui Jest test suite.
Reported by Annie.

fix template literal interpolations

---

tools/release-gh-pages.js

Changed release-gh-pages to use plain name
waiting for CircleCI
The GitHub pages are used by grommet-designer and the "hpe" theme should be associated with the latest default path.
coordinated with grommet-designer
shouldn't be needed

Changed release-gh-pages to use plain name

---

src/js/themes/hpe.js

Add `select.emptySearchMessage` pad which references button.option.pad value.
Will require grommet patch release to see styling come through. Functionality added by: https://github.com/grommet/grommet/pull/6815
Tested in grommet storybook in PR linked above.

Abstract button.option and apply emptySearchMessage pad

---

package.json

Updates grommet peer dependency to latest patch release which supports `theme.search.emptySearchMessage`.
Tested locally in DS site and GLCP.

Update grommet peerDependency

---

src/js/themes/hpe.js

Closes https://github.com/grommet/grommet-theme-hpe/issues/361
Adds 'xsmall' breakpoint to pageheader

Adds xsmall breakpoint to pageheader

---

package.json

Makes adjustments to build step and entry points in package.json so that npm install of stable branch will work.
Issues were:
1. `stable` branch didn't have a package.json but needs one for npm to know where to look (copies this over similar to how grommet stable branch works, grommet-exp, etc.)
2. adjusts the `main`, `module`, and `jsnext:main` paths to reflect the file structure (aligns with grommet setup). There is no `dist` folder in stable branch, instead point directly to the `index.js` files.
Will be able to text this locally with npm once merged.
Closes #99 
Closes #78

Fix build step and exports to allow npm install of branches

---

package.json

Reverts https://github.com/grommet/grommet-theme-hpe/pull/368/files which caused incorrect entry point for published npm package which has a different directory structure than our `stable` branches.

Revert package.json changes to fix npm publish

---

src/js/themes/hpePop.js

hpePop heading weight should not be altered by 5.1.0 product theme.

Keep weight 400 for hpePop

---

src/js/themes/hpe.js

Ensures h4 renders at 600 at medium size. When `size` prop is not explicitly defined on Heading level 4, it should still render at 600 weight.
The logic and current Figma styles confirm that h4 at medium  should be weight 600.
Tested locally in Design System site.
First h4 has `size="medium"`, Second h4 does not have size prop. Both render as weight 600.

Fix h4 heading weight

---

src/js/themes/hpe.js

This PR:
- Adjusts the direction of default (inline) notifications to `column`.
- Remove of `toast` specific direction since `column` is now the base direction.
- Adding `global` specific direction to retain existing `row` orientation.
- Updates Notification to use `Close` icon instead of `FormClose`.
Local in Design System site.
Related to https://github.com/grommet/hpe-design-system/issues/3627

Notification -- Incorporate staged changes from documentation site

---

src/js/themes/hpe.js

When toggle is outside of formfield, the hover state was causing the knob to shift down. This aligns with Figma by not adjusting the toggle border width on hover.
Locally.
BEFORE
https://github.com/grommet/grommet-theme-hpe/assets/12522275/3ce0ec35-3c26-4716-9e33-cf6bee7d49ee
AFTER
https://github.com/grommet/grommet-theme-hpe/assets/12522275/30cf498e-bd4b-4ddd-8237-bf0820f29dd9

Fix hover toggle

---

src/js/themes/hpe.js

Fixes Table pad by removing custom pad. Instead, we can rely directly on what comes by default from grommet since it aligns with our theming. This will feed from Table --> DataTable as well so they're in sync.
The note about needing the padding for when sortable no longer appears to be necessary (see screenshots below).
Local in design system site:
Showing focus/hover state in DataTable
Slack thread: https://hpe.slack.com/archives/C04LMJWQT/p1710861256038419

Fix Table pad

---

src/js/themes/hpe.js

Adds ToggleGroup button styling to align to toolbar buttons.
Local in Design System site.
Closes https://github.com/grommet/grommet-theme-hpe/issues/391
Added ToggleGroup styles.

Add ToggleGroup styles

---

src/js/themes/hpe.js

Abstract medium button iconOnly pad so that list.item.pinned.icon.pad can always be in sync.
Tested local in Design System site:
Related to https://github.com/grommet/grommet/pull/7204
Fix, the current misalignment is not as desired

Fix list.item.pinned.icon.pad to align with button pad

---

src/js/themes/hpe.js

adds `brand` for the icon color in Anchor
locally
Add icon color brand with new Grommet support
for hpe theme release

add icon color brand for anchor icon

---

package.json

Update peer dependency since `theme.anchor.icon.color` requires grommet v2.39.0.

Update grommet peer dependency

---

src/js/themes/colors.js
src/js/themes/hpe.js

This PR changes the icons that are being used for the ascending and descending 
on DS site 
These icons differ from industry standard direction (Material, Polaris, Carbon) and the general Grommet theme. We do not have strong rationale to differ, so we should swap these.
closes #403 
with new changes:
https://github.com/user-attachments/assets/a1bd5997-c3a8-4923-9655-a2989a8f4d91
yes

Change datatable icons

---

src/js/themes/colors.js

changes text color slightly in order to pass accessibility for our light colors 
locally on DS site
our text colors were not passing for accessibility 
closes #401 
with new color 
Fix text color contrast on background colors.

change text color to pass accessibility

---

src/js/themes/colors.js

Reverts grommet/grommet-theme-hpe#415
Status color changes will be included in next major theme version instead.

Revert "update status colors for theme"

---

src/js/themes/hpe.js

Updates clear selection styles based on https://github.com/grommet/grommet/pull/7397.
The `text.size` will be able to be removed in the theme update, but this is to align with current button font sizing.
https://github.com/grommet/hpe-design-system/pull/4207
Closes #410 
Fixed color contrast on "Clear selection" button in Select.

Apply updated clear selection styles

---

src/js/themes/hpe.js

Fixes styling of StarRating and ThumbsRating in FormField to behave like other grouped inputs (no border color in rest state).
BEFORE
AFTER

Fix ThumbsRating and StarRating in FormField

---

src/js/themes/hpe.js

Adds missing Pagination `selected.hover` styling.
BEFORE
https://github.com/user-attachments/assets/805162ba-06da-4a21-a961-4522c0266683
AFTER
https://github.com/user-attachments/assets/08571993-d4d4-48a2-83b5-a5ad2ff6efca

Added Pagination selected.hover styling

---

src/js/themes/hpe.js

Including all states styling for cta-primary and cta-alternate button kinds. While these kinds might be deprecated in the future, we are retaining them as part of grommet-theme-hpe for at least this major version since we had not previously marked them as deprecated.
cta-alternate uses "secondary" button styling
cta-primary uses "primary" button styling

Add all states styling for CTA buttons

---

src/js/themes/hpe.js

"option" styles are handled as separate logic to buttonKindTheme and buttonStates theme. This PR:
- Removes unused block of code in those functions that checked for "if kind === 'option'" even though the kind array we're mapping through doesn't use "option"
- Adds appropriate missing states for option styles: disabled, active (which applies when "option" has keyboard focus)
- Fixes incorrect reference to textColor token
BEFORE
https://github.com/user-attachments/assets/2971127b-671a-4587-87ca-14b4e24aa787
AFTER
https://github.com/user-attachments/assets/8565a6d4-1fe8-451a-9323-cb7ec5da5f3d

Fix states for select.option

---

src/js/themes/hpe.js

Fixes styling of TextInput and MaskedInput suggestions to align with new select.option styles.
MaskedInput doesn't have a drop specific extend, so needed to use the global extend for now. Will file grommet tickets for all the areas we're using extend.
BEFORE
https://github.com/user-attachments/assets/a5891db1-c962-4d30-b898-09bdc56f8d1c
https://github.com/user-attachments/assets/72dd9c87-72f3-408f-bde9-fc3a986e8c0d
AFTER
https://github.com/user-attachments/assets/dd2cd3b8-2483-4915-bb6f-914b951498be
https://github.com/user-attachments/assets/9852097c-3a39-4e2d-93bc-1e3374e8ce7c

Fix styling of TextInput and MaskedInput suggestions

---

src/js/themes/hpe.js

Only applies :hover styling in extend when item is not disabled. Adjusts appropriate instances and removes unnecessary block in select.control.extend.
Locally in sandbox/grommet-app.
BEFORE
AFTER
https://github.com/user-attachments/assets/5d058966-a363-4554-87a6-ad7d5070ab5e
https://github.com/user-attachments/assets/d2687b86-bc8d-4383-ae43-14d69ecbb82d

Only apply :hover when not disabled

---

src/js/themes/hpe.js

Removes an unneeded button.extend which was undesirably overriding the "readOnlyCopy" button padding. This block was added during initial QA (which was odd given it wasn't needed in past versions of the theme) -- the initial reason it was added may have been rooted in an incorrect token value which has now been resolved. Removing this block does not have any effect on icon-only sizes (see screenshots).

Removes unneeded button.extend which caused issues for DateInput + readOnlyCopy

---

src/js/themes/hpe.js

Fixes selected + disabled checkbox state. In doing so, identified a place where we were setting the "checked" state of checkbox to border: none (carry over from old theme version). We needed to remove this in order for the selected+disabled checkbox state to come through properly. It identified that the token value for `checkbox.default.control.selected.rest` and `checkbox.default.control.selected.hover` is incorrect. Proposing that we do an override in grommet-theme-hpe for the desired behavior, then remove this override once we do a minor version of hpe-design-tokens with any other first round refined styling/feedback.
BEFORE
AFTER

Fix checkbox disabled and selected states

---

src/js/themes/colors.js

In hpe-design-tokens we're not representing these "!" colors because they may not carry through to next brand iteration, so we did not want to carry over any baggage. We then removed any unused primitive colors from hpe-design-tokens, these two primitive colors were not used elsewhere in the semantic set so they were removed. For backwards compatibility, hard coding the existing value.
All other "!" primitive colors still exist.
Also fixing one other missing color reference. We removed "text-xweak" from design tokens for accessibility, but since we never marked it as "deprecated" in any previous grommet-theme-hpe, we will point it to "text-weak" so there is a value. In future major version of tokens we'll remove.

Fix primitive color reference

---

src/js/themes/hpe.js

Hard-coding opaque color value for rangeinput upper track color as workaround for existing grommet bug.

Hard code rangeinput upper track

---

src/js/themes/hpe.js

While we don't recommend use of `color` for HPE Design System. This PR provides a helpful fallback for color button hover styles to help accommodate some existing awkward logic in "color" + "kind" theme in [grommet](https://github.com/grommet/grommet/issues/7504). We also audited COM/GLP and they did not have instances of "color" Buttons, so the frequency of these occurring is low.
Without this, the "kind" specific hover styling would come through so we are just retaining the "color" as background color for consistency. Ideally in the future, the grommet "color" logic could provide more granular control for this styling.
NOTE: The text color still does receive the "kind" specific styling, but trying to go any deeper into the extend to control text color would require too much …

Provide helpful fallback for color prop buttons

---

src/js/themes/hpe.js

Fixes clear selection :focus styles to accommodate/align to the "padding" around options.
https://github.com/user-attachments/assets/13e73282-8dea-43e4-9d3c-ff4547378a95

Fix clear-selection focus style

---

.changeset/cuddly-files-change.md
src/js/themes/hpe.js

To align with shift away from "bold", fixes List primary key styling to use "medium" weight instead of bold.
Tested locally in storybook
BEFORE
AFTER
Closes #444

Use weight medium from `list.primaryKey`

---

.changeset/sixty-oranges-play.md
src/js/themes/hpe.js

Our overall desire is to head towards using disabled colors rather than opacity to drive "disabled" state. However, grommet does not currently support robust enough theme styling to enable this consistently across components.
For now, we will revert back to the existing "disabled opacity" approach and incorporate the "disabled colors" approach in the next major release once grommet supports this capability via: https://github.com/grommet/grommet/issues/7529
For RangeInput, since there are stacked disabled elements, I had to hard-code an opaque version of background-front + background-disabled for the thumb.
Locally in storybook. See "Fixes audit" in this Figjam: https://www.figma.com/board/N4X94MLi7mupnYIAO1yuhz/v6.0.0-audit?node-id=18-12852&t=qsN2pOw5Es914xez-1
Closes #447

Fix disabled input styling

---

.changeset/tender-rockets-do.md
src/js/themes/hpe.js

Adds missing disabled carousel icon color.
Local in storybook
BEFORE
AFTER
Closes #450

Add disabled carousel icon color

---

.changeset/rare-boats-taste.md
src/js/themes/hpe.js

NOTE: For versioning, I'd argue this should be a "fix" rather than a "minor" bump. Feels more likely that a team might render a Button kind (non-plain) in a table cell than use this "plain" pattern. So this would fix incorrect styling, but I am open to reviewer feedback.
Removes overly generic/opinionated extend selector in table body extend.
[The original introduction of this style](https://github.com/grommet/hpe-design-system/pull/1089/commits/cc75ca9b2aa805cd403dfd00053c18356920716c#diff-413a4b94bc47b0c7dfac6fe49ff6d52911c1af858f97f7024220a941a2cf1c74) references "plain buttons plus theme styling". 
I believe this referred specifically to the pattern where you might render a "plain" Button (button with children) inside a DataTable cell as a means of navigation ([See this …

Remove overly generic extend selector in `table.body`

---

.changeset/seven-bottles-fix.md
src/js/themes/colors.js

NOTE: Marking as draft for now in case any other "fixes" come in that we'd like to release prior to next minor version.
Adds graph-7 to pull in corresponding design token. We manually map dataVis-categorical colors to "graph" colors for grommet to know how to use smartly. v6.0.0 did most of this mapping but "graph-7" was not included.
Locally in storybook
```
<Meter
type="pie"
size="small"
values={[
{ value: 20 },
{ value: 20 },
{ value: 10 },
{ value: 10 },
{ value: 10 },
{ value: 10 },
{ value: 10 },
{ value: 10 },
]}
/>
```
BEFORE (with 8 graph elements, it's circling back around to 
AFTER

Add "graph-7" to correspond with final dataVis-categorical step

---

.changeset/heavy-dragons-design.md
package.json
yarn.lock

Updates to hpe-design-tokens v1.1.0
Tested in local project that new colors (icon-onStrong) and values (background-critical, .. other statuses) come through.

Upgrade hpe-design-tokens to next minor version

---

.changeset/clean-windows-clean.md
package.json
yarn.lock

Update dependency for hpe-design-tokens to ~1.2.0

Update dependency for hpe-design-tokens to ~1.2.0

---

.changeset/strong-tips-allow.md
src/js/themes/hpe.js

Enabled by https://github.com/grommet/grommet/pull/7576. Adds keyboard specific styles to TextInput and MaskedInput suggestions (which don't receive the global focus outline bc of combobox nature and therefore require an additional marker)
We can merge now (any team on latest upcoming Grommet release will inherit this fix) or wait until next major bump. My recommendation would be to merge now given it fixes an accessibility issue.
In this video, first using mouse and then using keyboard.
https://github.com/user-attachments/assets/1893d58d-dc52-44bb-a4d6-025feaa9d306
Locally in sample app.

Add keyboard specific styles for TextInput and MaskedInput suggestions

---

src/js/themes/hpePop.js

Adds hardcoded values for marketing typography scale for `hpePop` theme.
--------------------------
This pull request updates the `hpePop` theme in `src/js/themes/hpePop.js` to refine typography styles for headings, paragraphs, and text elements. Key changes include adjustments to font sizes, line heights, font weights, and the addition of new styles for better consistency and readability.
* Adjusted font weights (e.g., `weight` changed from `400` to `500` for headings).
* Updated font sizes and line heights for various heading levels, including the introduction of new `xlarge` and `xxlarge` styles for levels 1–6.
* Refactored the `extend` function to apply condensed font styles (`font-weight: 700; font-family: GraphikXXCondensed;`) for specific heading levels and sizes.
* Introduced a …

V2 alpha - Added marketing typography scale

---

.circleci/config.yml

Similar to other stable branches, ignore lint/build jobs on v2-alpha-stable.

Ignore v2-alpha-stable on lint/build jobs

---

src/js/themes/hpePop.js

Adds button styles for hpePop flavor. Also, adjust icon sizes to align with hpePop text sizes to ensure icon and label sizing in button is proportional.
Small button: 56px height
Medium button: 64px height
Large button: 72px height
-----------------------
This pull request enhances the `hpePop` theme in `src/js/themes/hpePop.js` by introducing customizable button sizes, improving button styling logic, and adding better support for light/dark mode handling. It also includes updates to icon sizing and fixes for known issues with hover styles and color handling.
* Added `createButtonSizes` and `popButtonSizes` to define consistent padding and size configurations for buttons, including support for `small`, `medium`, and `large` sizes. This includes specific padding for `iconOnly` and …

Add hpePop button styles

---

src/js/themes/hpePop.js

This pull request updates the typography styling in the `hpePop` theme to enhance readability and align with brand guidelines. The most significant change involves adding a new text transformation for specific heading levels and sizes.
* [`src/js/themes/hpePop.js`](diffhunk://#diff-a0cddec3d951e5c815bd69e89f05fd3a68e1af3fdc721421e7b1fdff3f48de91L282-R294): Renamed the variable from `font` to `fontStyle` for clarity, added `text-transform: uppercase;` to the font style for H1 headings of sizes `xlarge` and `xxlarge`, and adjusted the return value accordingly. This ensures that marquee page titles are displayed in uppercase, aligning with brand direction.

V2 alpha uppercase

---

.changeset/four-mirrors-yell.md
src/js/themes/hpe.js

Updates Tab styles in response to theme feedback.
Designs can be found: https://www.figma.com/design/ine5KzQ6rA41GboLZuG05A/Theme-feedback?node-id=454-34121&t=uvwx56V8XTiHzt7L-4
Locally in DS site: https://github.com/grommet/hpe-design-system/pull/5129
https://github.com/user-attachments/assets/ada3f2e0-4327-4828-b47a-b13852279215
Closes https://github.com/grommet/hpe-design-system/issues/5130

Update Tab styles

---

.changeset/healthy-suits-shake.md
src/js/themes/hpe.js

Adds "dot" treatment on unselected end of track to ensure appropriate affordance for end of track. At 3px by 3px, a minimum contrast ratio of 3:1 is required, which we more than exceed with the chosen semantic color.
rest + disabled states
Tested contrast ratios.
Closes https://github.com/grommet/grommet-theme-hpe/issues/461
Backwards compatible

Fix RangeInput styles to meet WCAG AA requirements

---

.changeset/forty-seas-cough.md
src/js/themes/hpe.js

Refine RangeInput styling for Firefox based on designer input. `pseudo` elements are not supported on selfclosing HTML tags (like input). Safari/Chrome are more forgiving on this, but Firefox is strict so the "dot" indicator is not coming through.
For Firefox only, we'll do a thin border around the track for the time being. Otherwise, we'd need to rebuild the component in grommet to have the "dot" styling across all browsers.
Locally on Firefox:
Closes https://github.com/grommet/grommet-theme-hpe/issues/461

Fix RangeInput styling for Firefox

---

.changeset/nine-emus-change.md
src/js/themes/hpe.js

The intended style is for the boxShadow (used for dark mode focus indicator) to not have any blur. This fixes that. Previously it was falling back to the default `2px` blur.
Local in DS site:
BEFORE:
AFTER:

Fix `global.focus.shadow.blur`

---

.changeset/heavy-fireants-walk.md
src/js/themes/hpe.js

Adds `global.focus.inset` for cases like "expand" control in DataTable where focus needs to be inset in the container to show.
**Note to reviewers**
@jcfilben @britt6612 We can discuss if this should be a "major" change (since it won't actually come through unless someone is on the grommet version that includes this enhancement) or a "minor" change (it would come through for teams that are on the latest, but it wouldn't break anything for teams on older versions).
Locally in Design System site.
Closes https://github.com/grommet/grommet/issues/7336

Add `global.focus.inset`

---

.changeset/heavy-fireants-walk.md
.changeset/nine-emus-change.md
.changeset/stupid-candles-eat.md
CHANGELOG.md
package.json

`yarn changeset version`
Tested in local sample app with latest grommet version and older grommet version to ensure to issues with `global.focus.inset`
With latest grommet functionality:

Updated version

---

.changeset/thin-cherries-own.md
src/js/themes/hpe.js

In conjunction with https://github.com/grommet/grommet/pull/7655, fixes alignment of radiobutton checked icon on browsers like Safari.
Local in storybook.
https://github.com/user-attachments/assets/1815df66-2d01-4cf2-8d77-47ad12c5c0b7

Fix RadioButton alignment across browsers

---

.changeset/hungry-donuts-crash.md
src/js/themes/hpe.js

It is beneficial to drive what the font-weight string "bold" should resolve to via the theme. A few major versions ago, we instructed that "bold" treatment should really now use "medium" to evolve with HPE's brand, however leaving it up to individual teams to implement this poses additional remapping work and room for divergence.
This PR changes the behavior of Text / Heading such that:
- If the caller passes `weight="bold"`, it will resolve to whatever we define "bold" to mean in the theme (at the current state, 500)
- If the caller passes weight as a string/number (for example, `weight={800}` or `weight="800"`), we will respect the specific weight they passed.
This allows the concept of "bold" to be theme-driven, while still allowing the caller to override via the specific numeric …

Enhance theme-driven "bold" weight

---

.changeset/perfect-ladybugs-hunt.md
src/js/themes/hpe.js

Table theme object was missing token mappings for header and footer cell paddings, creating a discrepancy between hpe-design-tokens and grommet-theme-hpe. Previously, header and footer cells had incorrectly rendered as 36px instead of 48px.
Locally in DS site (AFTER)
Footer cell
Header cell

Fix headerCell, footerCell padding

---

src/js/themes/hpe.js

Related to changes here: https://github.com/grommet/grommet/pull/7804
Adds the updated t-shirt size to the theme dataTable.resize.padding.vertical property

Add DataTable resizer padding t-shirt size

---

package.json
src/js/themes/prism.js
yarn.lock

Update colors for v8 codeblocks
designs: https://www.figma.com/design/UzfMeRUpDTDwwSFNfZgPBq/Untitled?node-id=3-139&t=u2VSOxgDhZ7Tx3PS-1

updated v8 theme for code blocks colors

---

src/js/themes/colors.js

The red, orange, yellow, and teal colors have been deprecated in tokens v2 and are not intended for use in Landmark.

Remove red, orange, teal, and yellow decorative colors
