- package.json
- yarn.lock
Getting the theme up to date before the massive changes are coming. (Mainly for verification purposes)
> Bump styled-component version to 5.0.0

- src/js/index.js
Updating values according to our team meeting.
> Changed button radius and pad

- src/js/index.js
Input weight was in global.colors but it should just be in global
> Move input weight to global

- src/js/index.js
Fixes anchor styling that had been removed in previous PR.
> Update anchor to latest approved designs

- src/js/index.js
> Update colors and anchor styles

- src/js/index.js
small tweaks than include appropriate transparency
> Update background contrast

- src/js/index.js
Corrected position of alpha values
> Updated background-contrast

- src/js/index.js
set global input padding to horizontal: 'small', vertical: 'xsmall'
> Update input padding

- src/js/index.js
Updating usage of text-xweak in formfield text to use text-weak to match most recent designs.
> Update formfield text to use text-weak

- src/js/index.js
> Deprecating accent and neutral colors

- src/js/index.js
Dependent on this grommet PR: https://github.com/grommet/grommet/pull/3974
> Allow input to respect font line-height

- package.json
- src/js/index.js
- yarn.lock
The following are updates reconciling text / formfield colors, as well as some drop and select specific styling. Links are to Figma files for reference.
- [text.dark](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-color?node-id=0%3A1)
- [disabled-text](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-color?node-id=0%3A1)
- [Drop Shadows](https://www.figma.com/file/eZYR3dtWdb9U90QvJ7p3T9/hpe-color?node-id=405%3A25)
- [input text color](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/hpe-select?node-id=103%3A140)
-[select options text size](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/hpe-select?node-id=103%3A140)
> Latest text and formfield colors plus drop and select styling

- src/js/index.js
- yarn.lock
Addresses: https://github.com/hpe-design/design-system/issues/520#issuecomment-619205140
Summary:
- Updates 'active-background' to be 'background-contrast'
- Updates 'selected-background' to use 'green' instead of brand
- Reduces Select Option Box vertical padding
Note: The comments in the linked issue point to selected-text as incorrect, however the selected background was updated and therefore selected-text should remain 'text-strong'
[Figma File](https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140)
Tested on Design System Site:
> background color adjustments, plus option pad

- src/js/index.js
Adding to margin for accordion and undefined for hover color change.
> add in margin & hover to accordion

- src/js/index.js
Tab color should now be text-strong instead of text.
> Make tab color text-strong

- src/js/index.js
Pending on https://github.com/grommet/grommet/pull/405.
This PR is applying new styles for the `default` and `secondary styles while adapting the new button theme structure. Stay tuned.
> Updated new button styles

- src/js/index.js
Following up on PR https://github.com/grommet/grommet/pull/4042, where we added `panel.border` option, along with some refactoring on the theme structure.
A POC for the border work can be found in this example https://storybook.grommet.io/?path=/story/accordion--themed.
This PR fixes the border issue for https://github.com/hpe-design/design-system/issues/512
> Changed accordion styles

- src/js/index.js
- yarn.lock
Dependent on: https://github.com/grommet/grommet-theme-hpe/pull/73
Brings FormField label weight (medium/500) in line with designs: https://www.figma.com/file/3fkwBelW5UsCbfwdDCJkT8/HPE-Form-Templates?node-id=0%3A1
> update FormField label weight

- src/js/index.js
- yarn.lock
Updating tabs styling based on new grommet theming capabilities which allows us to close https://github.com/hpe-design/design-system/issues/789
> Update tabs so border extends

- src/js/index.js
Updates styling to align with functionality provided by [this PR](https://github.com/grommet/grommet/pull/4163)
> Update button styling based on kind=option

- src/js/index.js
- yarn.lock
Closes https://github.com/hpe-design/design-system/issues/920
Adds disabled styling for Tab:
- border color
- font color
[Figma](https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=0%3A1)
Testing:
Applied to aries.js and tested on Design System site.
> add tab disabled styling

- src/js/index.js
This PR adds a size for the calendar icon 
yes
visual
The icon used in grommet is to large for what is in the designs 
issue #1042 in design system
> add size for dateinput icon

- src/js/index.js
- src/js/interim.js
- src/js/v2migration.js
- yarn.lock
This PR suggests an interim theme that will mitigate the breaking changes to the design-system theme upgrade.
Yes, done.
None, yet.
Follow up on our GLC migration.
The design-system is providing an interim theme that helps mitigate the breaking changes of the theme upgrade. 
More notes on where the interim theme could be found will be helpful as well.
> Added interim theme

- package.json
Added grommet as a peer-dependency for the theme users.
> Added grommet as peer dependency

- src/js/index.js
- yarn.lock
Adds newly available sorting icons for DataTable
Local Design System site
https://github.com/grommet/hpe-design-system/issues/1077
Updating icons used in ascending/descending DataTable column sorting.
> Add DataTable sort icons

- package.json
https://github.com/grommet/grommet-theme-hpe/issues/162
> Changed peer dependency to grommet latest release

- src/js/index.js
Add validation ok and warning to the theme 
none
none
issue #1423 in design system
https://github.com/grommet/hpe-design-system/issues/1423
no
no
> add validation colors

- src/js/index.js
Adds styling for pagination button.
Tested locally in Design System site.
Backwards compatible (introducing new theming)
Added styling for Pagination.
> Add pagination button styling

- src/js/index.js
Adds disabled styling for pagination button.
> Pagination should apply text-weak on disabled control

- src/js/index.js
> add theme for spinner

- src/js/index.js
update the  icon to match the designs 
part of https://github.com/grommet/hpe-design-system/issues/1745
> change icon to match designs

- src/js/index.js
This PR changes the hover from transparent to have a background
based on  https://github.com/grommet/hpe-design-system/issues/1784
closes #1818
https://github.com/grommet/hpe-design-system/issues/1818
> add hover to toolbar button

- src/js/themes/hpe.js
Reverts grommet/grommet-theme-hpe#223
> Revert "add hover for primary button"

- src/js/themes/hpe.js
update active button to have text `text-strong` 
tested in the design system site
designs call for `text-strong`
closes #228 
It will change how active button was before
yes
> fix active button text color

- src/js/themes/hpe.js
FIxes the colors had the dark and light backward. Noticed on the site that the colors were switched
> fix hover color

- src/js/themes/hpe.js
Fixes a lint error. Adds a trailing comma in the page theme
> Lint fix, add trailing comma

- src/js/themes/hpe.js
Adds theme for banner notification
DS site
view changes https://deploy-preview-2363--keen-mayer-a86c8b.netlify.app/templates/global-banner-notifications?q=glo
completes banner notification issue
yes
> add theme for banner notification

- src/js/themes/hpe.js
Takes out the trash icon
design site
closes #2457
yes
> take out trash icon

- src/js/themes/hpe.js
adds new breakpoints from aries site
all of this was locally within design system site
breaking change of break points
announcement with migration notes
> add breakpointts from aries theme and pad for page

- src/js/themes/hpe.js
- yarn.lock
Adjusted anchor gap to `xsmall` to align with Button and desired styling.
In DS Site.
Related to https://github.com/grommet/hpe-design-system/issues/2562
Changes anchor gap.
Changed Anchor gap to `xsmall` to align with Button styling.
> Set anchor gap to xsmall

- src/js/themes/hpe.js
Adds accordion hover background.
Tested locally in DS Site.
Related to https://github.com/grommet/grommet/issues/6176
https://user-images.githubusercontent.com/12522275/173641837-5f3c7799-43fd-407a-b91b-b70aa113db8d.mov
- Added `background-contrast` hover styling to Accordion panel.
> Add accordion hover

- package.json
- src/js/themes/hpe.js
- yarn.lock
Adds a step size for tabs for xsmall and xlarge screen sizes
Tested in this pr: https://github.com/grommet/hpe-design-system/pull/2668/files
Backwards compatible
Added step size for xsmall and xlarge screens
> Responsive tabs step

- src/js/themes/hpe.js
Change the color for the spinner
design system site
There was a misalignment between figma spinner and the site. 
Think the intentions were to have the color `green` however in the base.js it has `brand` for the color so that needed to change
closes #2755
> Fix spinner color and size

- src/js/themes/hpe.js
> Brand refresh b

- src/js/themes/hpe.js
> Brand refresh c

- src/js/themes/hpe.js
> option a - rounded buttons only

- src/js/themes/hpe.js
> Brand refresh a

- src/js/themes/backgrounds.js
- src/js/themes/hpe.js
- src/js/themes/index.d.ts
- src/js/themes/index.js
Closes https://github.com/grommet/hpe-design-system/issues/2824 by adding a `backgrounds` theme object with namespaces.
> Makes background gradients and textures available to theme

- src/js/themes/backgrounds.js
Flattens backgrounds theme structure.
> Backgrounds restructure

- .circleci/config.yml
- README.md
- package.json
- src/js/index.js
- src/js/themes/hpe.js
- tools/release-gh-pages.js
Cleans-up "NEXT" specific items pre-release.
> NEXT cleanups pre-release

- src/js/themes/colors.js
- src/js/themes/hpe.js
Merging into NEXT branch for impact / evaluation. Applies modified typography sizes, line-heights, weights, and colors for headings, paragraphs, text, and form field inputs.
To investigate:
Questions:
- Do text-weak and text-xweak values need to be adjusted to play better with new text-strong and text values?
- FormField text styling - probably should bump weight down for label and input value. Input value color and placeholder color are too similar when at lighter weight. Use new text-strong for input value color?
- Do border colors need to be adjusted to play better with thinner font weights?
- Current border colors were recently made with opacity. This causes issues when borders overlap such as in Accordion where adjacent panel borders appear darker than edge panels.
- Re-calculate …
> 3020 typography impact eval

- src/js/themes/colors.js
- src/js/themes/hpe.js
> Font weight config changes

- src/js/themes/colors.js
- src/js/themes/hpe.js
> extend heading, paragraph, text to accommodate varying weights

- src/js/themes/colors.js
- src/js/themes/hpe.js
modify font weights for buttons, dataTable, nameValuePair, pagination, tab, table, tag
> 3020 typography impact eval - modify font weights for buttons, dataTable, nameValuePair, pagination, tab, table, tag

- package.json
- src/js/themes/colors.js
- src/js/themes/hpe.js
- src/js/themes/hpeWeb.js
- src/js/themes/index.d.ts
- src/js/themes/index.js
Implements latest brand direction for Product and Web theme experiences.
https://github.com/grommet/hpe-design-system/issues/3102
> update with latest on-brand specs

- src/js/themes/hpe.js
fix font weights and remove extraneous properties
> fix font weights and remove extraneous properties

- tools/release-gh-pages.js
- tools/release-next-stable.js
- tools/release-stable.js
Simple git had a major release which required updated syntax for declaring `git` variable. I can't fully test this until we merge since it runs in CircleCI env only.
> Update simple git syntax

- src/js/themes/hpe.js
> Add color text-strong to active paginated button

- src/js/themes/hpe.js
> FileInput - update remove icon and hover font color

- src/js/themes/hpe.js
> remove margin from formfield error icon

- src/js/themes/hpe.js
- webpack.config.babel.js
Aligned webpack externals with peer dependencies
grommet-designer dynamic theme loading
backwards compatible
I think this should be automatically handled by the final app bundler packaging. But, would be good to double check with something like the hpe-design-system site.
> Aligned webpack externals with peer dependencies

- src/js/themes/index.js
Export audit as hpe so that caller doesn't have to do any other config changes.
> AUDIT branch - Export audit as hpe

- src/js/themes/audit.js
- src/js/themes/index.js
> Audit brand - refine annotation styling

- .circleci/config.yml
- package.json
- tools/release-tokens-stable.js
Adds CircleCI config to release TOKENS-stable branch.
> Add release-tokens-stable

- src/js/themes/colors.js
> Add color references from tokens

- package.json
- src/js/themes/hpe.js
- yarn.lock
Closes https://github.com/grommet/hpe-design-system/issues/3317 by adjusting tag's default vertical padding to 5px, which results in 5px pad + 1px border = 'xsmall' and an overall height of 36px instead of 38px which aligns with input and button dimensions.
> update tag height

- .circleci/config.yml
Updates the node version on the circleci config for the stable branch
> Update config.yml to use node 18

- package.json
Adds fix for npm install to the NEXT branch
> Fix build step and exports to allow npm install of branches - NEXT branch

- package.json
> Updated v5.1.0

- package.json
> Updated v5.1.1

- src/js/themes/hpe.js
Adds `kind: toolbar` for Data controls to align with functionality introduced by: https://github.com/grommet/grommet/pull/7025
Tested in Grommet PR.
Closes #373
> Add toolbar kind to data object

- package.json
- src/js/themes/hpe.js
- Remove override to Notification Anchor styling to align with Figma
- Update grommet peerDependency for Data+friends
Yes.
> Incorporate changes for notification anchor styling and peerDependency

- package.json
Pre-release step, updating package.json version number.
> Update package.json to v5.2.0

- .circleci/config.yml
> Point to new NPM token

- .circleci/config.yml
> Point to new NPM token on stable

- src/js/themes/hpe.js
Trivial comment change to re-run release-stable/gh-pages.
> Trivial comment change

- src/js/themes/hpe.js
Adds styling from readonly inputs.
> Add readOnly styling

- src/js/themes/index.js
Add use client to index.js to support use in NextJS App router which assumed SSR unless specified.
> Add use client to index.js

- package.json
Update package.json for v5.3.1
> Update package.json for v5.3.1

- package.json
Updated package.json to v5.4.0, update peer dependency for grommet to v2.37.0 since that's necessary for theme effects to take effect.
> Updated v5.4.0

- package.json
> Updated v5.7.0

- src/js/themes/colors.js
updates theme notification status colors 
locally
accessibility
> update notification colors for theme

- src/js/themes/hpe.js
Bottom border was not properly getting removed in case of certain grouped cells
> Fix bottom border on last row of DataTable

- package.json
Updated version in package.json.
> Updated v6.0.0

- src/js/themes/colors.js
- src/js/themes/hpe.js
- src/js/themes/hpePop.js
- src/js/themes/prism.js
> Apply prettier formatting

- .changeset/cuddly-files-change.md
- .changeset/dry-beds-leave.md
- .changeset/nervous-plants-collect.md
- .changeset/rare-boats-taste.md
- .changeset/sixty-oranges-play.md
- .changeset/tender-rockets-do.md
- CHANGELOG.md
- package.json
> Updated version v6.0.1

- .changeset/eight-crews-build.md
- package.json
- yarn.lock
Update to v1.3.0 on hpe-design-tokens.
> Update hpe-design-tokens dependency to v1.3.0

- .circleci/config.yml
- package.json
Adds script to update `v2-alpha-stable` whenever we merge something to `v2-alpha`.
> Add release-v2-alpha-stable scripts

- .changeset/gentle-suns-rest.md
- package.json
> Add support for React 19 to peerDeps

- src/js/themes/hpe.js
This PR updates the new theme changes for accordion component
- add theme container pad for icon
- add theme container pad for label
locally in DS site
Yes
> Update accordion icon and label containers pad

- src/js/themes/hpe.js
Add theme updates for tab
- add tab gap
- add tabs padding - vertical and horizontal
> Add theme updates for tab

- src/js/themes/hpe.js
Update checkbox theme changes
Yes
> Update checkbox theme changes

- src/js/themes/hpe.js
- Update radioButton and radionButtonGroup theme objects
- update radio button horizontal gap
- update radio button group container gap
YES
> Update radioButton and radionButtonGroup theme objects

- src/js/themes/hpe.js
Update paragraph theme object
- add skeleton gap them object
Yes
> Update paragraph theme object

- src/js/themes/hpe.js
- Add data summary theme object
- add data summary vertical margin theme object
- add data summary separator horizontal margin theme object
Yes
> Add data summary theme object

- src/js/themes/hpe.js
> Add distribution theme object

- src/js/themes/hpe.js
- update title container  horizontal pad theme object for small, medium and large sizes
Yes
> Update calendar title container pad for different sizes

- src/js/themes/hpe.js
- Add header gap theme object
Yes
>
> Add header gap theme object

- src/js/themes/hpe.js
- add cards grid columns object
- add cards grid gap 
Yes
> Add cards theme object

- src/js/themes/hpe.js
- Add button margin theme object
- Update icon size to medium
> Update date input theme object

- CHANGELOG.md
- package.json
> Updated to v7.0.2

- src/js/themes/hpe.js
- yarn.lock
This PR fixes the background color of the primary cta button on light and dark mode
before:
after:
This also fixes the icon color in the secondary cta button on hover
before: 
on hover
after:
on hover
locally in DS site on v8 branch
There was already a fix in the extend that was there to override the color prop 
I added the `kind === 'cta-primary'` as another check along with `kind === 'primary'`
`cta-alternate` button inherits from the `buttonStatesTheme.hover.secondary` so in there the hover color is set to `text-strong` which resolves to `#ffffff` (white) so this is effecting the icon to change to white on hover. 
need for v8 theme
> fix cta primary button background and cta secondary icon color
